export interface Drivers{
    driver_id: string,
    licence_no: string,
    full_names: string,
    route: string,
    vehicle_name: string,
    vehicle_model: string,
    vehicle_year: number,
    vehicle_plate: string,
    email_addr: string,
    phone_no: string,
    alt_no: string,
    driver_address: string,
    driver_city: string,
    driver_country: string,
    postal_code: number,
    date_created: string,
    date_modified: string,
}